name: Publish to NPM
"on":
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install package
        id: install
        run: |
          npm install -g npm
          npm i
      - name: Publish to Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx vsce publish
