name: Run style checks and unit tests
'on':
  push: {}
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm
      - name: Install package
        id: install
        run: |
          npm ci
      - name: Run linting
        id: lint
        run: |
          npm run lint
