name: Create Release Pull Request
"on":
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
jobs:
  release-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release
        uses: actions/github-script@v3
        id: release
        with:
          script: |
            let release = null;
            if (context.payload.inputs && context.payload.inputs.tag) {
              const tagName = context.payload.inputs.tag;
              // find Pull Request by number fom input
              const releasesResponse = await github.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              for (let releaseItem of releasesResponse.data) {
                if (releaseItem.tag_name !== tagName) continue;
                release = releaseItem;
                core.info(`Found release ${release.name}`);
                break;
              }
            }
            if (context.payload.release){
              // get Release from event payload
              release = context.payload.release;
            }

            if (!release) {
              throw new Error(`Cannot find Release`);
            }

            core.setOutput('target', release.target_commitish);
            core.setOutput('branch', `release/${release.tag_name}`);
            core.setOutput('id', release.id);
            core.setOutput("url", release.html_url);
            core.setOutput('tag', release.tag_name);
            core.setOutput('name', release.name);
            core.setOutput('body', release.body);
            return true;
      - name: Checkout Release target branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.release.outputs.target }}
      - name: Set version
        id: set-version
        run: |
          npm config set git-tag-version false
          npm version ${{ steps.release.outputs.tag }} --allow-same-version
      - name: Add new release to CHANGELOG.md
        id: changelog
        uses: vemel/nextchange
        with:
          github-actions-managed: true
          release: ${{ steps.release.outputs.tag }}
          clear: true
          set: ${{ steps.release.outputs.body }}
      - name: Clear Unreleased in CHANGELOG.md
        id: clear-unreleased
        if: ${{ steps.version.outputs.is-prerelease == 'false' }}
        uses: vemel/nextchange
        with:
          github-actions-managed: true
          release: Unreleased
          clear: true
      - name: Commit changes
        id: commit
        run: |
          git commit -am "Bump version to $VERSION"
          git push
      - name: Publiush to Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx vsce publish
