name: Update packages
"on":
  workflow_dispatch: {}
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install bs4 pypistats requests
      - name: Update packages
        run: |
          python ./get_packages.py
      - name: Commit changes
        run: |
          git commit -am "Update packages"
          git push
